controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    # joint_state_broadcaster:
    #   type: joint_state_broadcaster/JointStateBroadcaster

    Arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

Arm_controller:
  ros__parameters:
    publish_rate: 100
    action_ns: "follow_joint_trajectory"  # Specify the correct action namespace
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_partial_joints_goal: true
