controller_list:
- name: arm_controller
  action_ns: follow_joint_trajectory
  type: joint_trajectory_controller/JointTrajectoryController
  default: true
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6





# controller_manager:
#   ros__parameters:
#     update_rate: 100
#     joint_trajectory_controller:
#       type: joint_trajectory_controller/JointTrajectoryController
#       joints:
#         - joint_a1
#         - joint_a2
#         - joint_a3
#         - joint_a4
#         - joint_a5
#         - joint_a6
#       command_interfaces:
#         - position
#       state_interfaces:
#         - position
#         - velocity
#       allow_partial_joints_goal: false

#     mock_hardware:
#       type: mock_components/GenericSystem
#       joints:
#         - name: joint_a1
#           command_interfaces: [position]
#           state_interfaces: [position, velocity]
#         - name: joint_a2
#           command_interfaces: [position]
#           state_interfaces: [position, velocity]
#         - name: joint_a3
#           command_interfaces: [position]
#           state_interfaces: [position, velocity]
#         - name: joint_a4
#           command_interfaces: [position]
#           state_interfaces: [position, velocity]
#         - name: joint_a5
#           command_interfaces: [position]
#           state_interfaces: [position, velocity]
#         - name: joint_a6
#           command_interfaces: [position]
#           state_interfaces: [position, velocity]
